"""Run the data quality checks in sql/quality and write reports/data_quality.md.

Each check file returns the rows that violate it and declares its severity in a
header comment. Critical violations fail the pipeline after the report is
written; warnings are reported only. Profile files are descriptive tables.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

import pandas as pd

from xsell.config import Config
from xsell.data.convert import read_manifest
from xsell.db import connect, run_sql_file
from xsell.errors import XsellError
from xsell.logging_utils import get_logger
from xsell.reporting import markdown_table, write_text

logger = get_logger("xsell.quality")

SEVERITIES = ("critical", "warning", "profile")
SAMPLE_ROWS = 5
_HEADER = re.compile(r"^--\s*(\w+):\s*(.+?)\s*$")


class QualityError(XsellError):
    """At least one critical data quality check failed."""


@dataclass(frozen=True)
class CheckResult:
    name: str
    severity: str
    description: str
    violations: int
    rows: pd.DataFrame

    @property
    def status(self) -> str:
        if self.severity == "profile":
            return "info"
        if self.violations == 0:
            return "pass"
        return "FAIL" if self.severity == "critical" else "warn"


def read_header(path: Path) -> dict[str, str]:
    """Key: value pairs from the leading comment block of a SQL file."""
    header = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.startswith("--"):
            break
        match = _HEADER.match(line)
        if match:
            header[match.group(1).lower()] = match.group(2)
    severity = header.get("severity")
    if severity not in SEVERITIES:
        raise XsellError(f"{path.name}: header must declare severity as one of {SEVERITIES}, got {severity!r}")
    if not header.get("description"):
        raise XsellError(f"{path.name}: header must include a description")
    return header


def quality_params(config: Config) -> dict[str, float]:
    return {
        "age_min": config.quality.age_min,
        "age_max": config.quality.age_max,
        "income_max": config.quality.income_max_eur,
    }


def run_checks(config: Config) -> list[CheckResult]:
    files = sorted((config.paths.sql_dir / "quality").glob("*.sql"))
    if not files:
        raise XsellError(f"no quality checks found in {config.paths.sql_dir / 'quality'}")
    results = []
    with connect(config, read_only=True) as connection:
        for path in files:
            header = read_header(path)
            rows = run_sql_file(connection, path, quality_params(config))
            rows = rows if rows is not None else pd.DataFrame()
            result = CheckResult(path.stem, header["severity"], header["description"], len(rows), rows)
            results.append(result)
            if result.severity != "profile":
                logger.info("%-34s %-8s %s (%d rows)", result.name, result.severity, result.status, len(rows))
    return results


def render_report(results: list[CheckResult], manifest: dict | None) -> str:
    checks = [result for result in results if result.severity != "profile"]
    profiles = [result for result in results if result.severity == "profile"]
    lines = ["# Data quality report", ""]
    lines.append("Generated by `python -m xsell quality` from `sql/quality/`. Each check returns its violating rows.")
    lines.append("Critical checks stop the pipeline; warnings are reported and handled as described.")
    lines.append("")
    if manifest:
        share = manifest.get("sample_share")
        sample = "all customers" if share is None else f"deterministic {share:.0%} customer sample"
        lines.append(
            f"Source: `{manifest['source']['zip_name']}` (SHA-256 `{manifest['source']['zip_sha256'][:12]}...`), "
            f"{manifest['rows']:,} rows, {manifest['customers']:,} customers, {sample}."
        )
        lines.append("")

    lines.append("## Checks")
    lines.append("")
    summary = pd.DataFrame(
        {
            "check": [result.name for result in checks],
            "severity": [result.severity for result in checks],
            "status": [result.status for result in checks],
            "violating rows": [result.violations for result in checks],
            "description": [result.description for result in checks],
        }
    )
    lines.append(markdown_table(summary))
    for result in checks:
        if result.violations:
            shown = min(SAMPLE_ROWS, result.violations)
            lines += ["", f"### {result.name} ({shown} of {result.violations:,} violating rows)", ""]
            lines.append(markdown_table(result.rows.head(SAMPLE_ROWS)))

    for result in profiles:
        lines += ["", f"## {result.description.rstrip('.')}", ""]
        lines.append(markdown_table(result.rows) if result.violations else "None.")
    return "\n".join(lines)


def run_quality(config: Config) -> list[CheckResult]:
    """Run all checks, write the report, raise QualityError on critical failures."""
    if not config.paths.warehouse.is_file():
        raise XsellError(f"warehouse not found at {config.paths.warehouse}; run `python -m xsell warehouse` first")
    results = run_checks(config)
    report = write_text(
        config.paths.reports_dir / "data_quality.md",
        render_report(results, read_manifest(config.paths.cache_dir)),
    )
    logger.info("wrote %s", report)
    failed = [result.name for result in results if result.status == "FAIL"]
    if failed:
        raise QualityError(f"critical data quality checks failed: {', '.join(failed)} (see {report})")
    return results
